### ISSUE TITLE
Playground based on minikube?

### ISSUE THREAD

**Issue by sevein** [draios/kubernetes-sysdig-metrics-apiserver#3]
This is an open question. I started with a custom k8s cluster supported by Vagrant plus kubeadm because I thought it would provide greater flexibility when it comes to set up the cluster
But I recognize that supporting minikube could be even nicer because that's the tool and the workflow that developers are more confortable with.

I still need to confirm that it works but the following seems possible:

    $ minikube start --extra-config kubelet.EnableCustomMetrics=true

But we'd also need to confirm that the Sysdig Agent can be installed.

Related: https://github.com/vishen/k8s-custom-metrics.

**Comment by tembleking** [comment]
Minikube is completely supported using [eBPF](http://www.brendangregg.com/ebpf.html).
Running the agent with eBPF is as easy as setting the `SYSDIG_BPF_PROBE=""` env var.
The empty string tells the probe loader to build the probe itself rather than using an already-built probe.
If the user has already built a probe separately, the location of the probe can be specified instead of the empty string.
